### ISSUE TITLE
Door Remotes Don't Update Light Indicators On Door Sprite

### ISSUE THREAD

**Issue by Samsterious** [arcadia-station/arcadia-station#1157]
When using a Door Remote to bolt or EA a door, the red or flashing yellow indicators do not light up until the door is de-powered and powered again.

**Comment by Vordenburg** [comment]
Does this occur on upstream?

**Comment by jicksaw** [comment]
Yes, happens on upstream too. There's an [open PR] on upstream that might touch this stuff, but as it is it doesn't fix this.

[open PR]: https://github.com/space-wizards/space-station-14/pull/13884

**Comment by Samsterious** [comment]
Noted. I'll check upstream's issues too, next time. I thought remotes were a Nyano thing fsr pft

**Comment by Vordenburg** [comment]
Should've been resolved by #1278
