### ISSUE TITLE
Altars should be constructible

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#1215]
more yaml bait

**Comment by Vannn4** [comment]
What should the recipes be? If i know that i could work on this

**Comment by Vordenburg** [comment]
Plasteel, bluespace, maybe some gemstones or other rare/unused goodies from salvage. Maybe gold or silver? Throwing out some ideas here.

**Comment by Vordenburg** [comment]
Resolved by #1591
