### ISSUE TITLE
Mob AI can see things they shouldn't be able to

### ISSUE THREAD

**Issue by DEATHB4DEFEAT** [arcadia-station/arcadia-station#1341]
**Reproduction**
Spawn an invisible entity with NanoTrasen faction
Spawn a hostile mob
Hostile mob attacks invisible entity

**Screenshots**
![image](https://user-images.githubusercontent.com/77995199/223880153-bbb4b6a3-5475-4765-a535-5fe8015e161d.png)
![image](https://user-images.githubusercontent.com/77995199/223880162-554a1182-f2ae-4a6f-b8f3-c43a1ba642cb.png)

**Additional context**
Often experiencing this on ParkStation, as the AIeye is an invisible entity.
**This also occurs with AdminObserver**

**Comment by Elijahrane** [comment]
going to say this is almost certainly an upstream issue

>as the AIeye is an invisible entity.

Does something immaterial need an AI faction? Just removing it would be a decent workaround for you

**Comment by Vordenburg** [comment]
This should be forwarded upstream.
