### ISSUE TITLE
Air Alarms Have Zero Default Maxima for Undesired Gases

### ISSUE THREAD

**Issue by Torun-S** [arcadia-station/arcadia-station#1361]
## Description
Air alarms trigger a lockdown when, among other things, any type of gas' temperature or concentration goes outside the defined range. The defaults pertain to maintaining a standard atmospheric mix, 21/79 O/N and zero anything else.

The problem lies with the "zero anything else"; When a gas leak occurs and an atmos tech decides to resolve it cleanly by means of portascrubbers or simply letting the floor scrubber do its thing, it is often excessively difficult to actually bring down the foreign gas concentration to absolute zero, and so the Air Alarm may continue to randomly trigger until the Danger Above is set just one step higher.

I hate for engineers to have to adjust sometimes several alarms whenever a leak happens or the chef messes up with the deep fryer and lets off a puff of steam (yes, that's a trigger too). The defaults of all gases for Danger Above should be set slightly above zero so that clearing the leak isn't followed by a bunch of "false-positives".

**Reproduction**
1. Go to any map and pick a room with an air alarm and firelocks
2. Release some tritium in it to simulate a leak and observe the firelocks close
3. Use a portable scrubber in one place to clear the room
4. Be hard-pressed in getting the firelocks to open
5. If they do open, take a while to observe that they may randomly decide to close again after the scrubber is deactivated.

**Comment by Vordenburg** [comment]
If this is still an issue, it should be brought to the attention of the SS14 repo.
