### ISSUE TITLE
Colorblindness trait in shift-click menu

### ISSUE THREAD

**Issue by JeanGrenouille010101** [arcadia-station/arcadia-station#1409]
## Description
Colorblindness trait does not apply to shift-click menu

**Reproduction**
1. Select colorblind trait
2. Shift click on crew member
3. See full color image of crew member

**Screenshots**
![Evedince](https://user-images.githubusercontent.com/67086183/227808943-7e9e03ab-606c-476d-8238-b4e782495033.png)

**Comment by Elijahrane** [comment]
This is due to the difference between screen shaders and sprite shaders

I'm not sure what the *best* solution is but it'd probably not be that hard to make a sprite shader

**Comment by Vordenburg** [comment]
PostShaders override interaction outline, so a sprite-based shader wouldn't work. It'd be a mess to add it to every entity in view, too, for this one case. This is ultimately going to be something that will have to be figured out at the engine level, if at all.
