### ISSUE TITLE
PebbleStation has ProtectedGrid component

### ISSUE THREAD

**Issue by hecksadecimal** [arcadia-station/arcadia-station#1517]
https://github.com/Nyanotrasen/Nyanotrasen/blob/ff342d48c12d6aa03b7e4ac1766f5b732a445018/Resources/Maps/pebble.yml#L4408

This should be removed, players can't effectively fix the station in the event of meteors or bombs.

Admins have to delete this component in-round when we're playing on pebble until this gets fixed in the prefab.

**Comment by Elijahrane** [comment]
This has been fixed
