### ISSUE TITLE
Wielding a weapon makes you invulnerable to Disarm

### ISSUE THREAD

**Issue by Vordenburg** [arcadia-station/arcadia-station#1586]
Introduced by https://github.com/space-wizards/space-station-14/pull/16275

**Comment by Elijahrane** [comment]
https://github.com/space-wizards/space-station-14/pull/17520 Removes immunity to disarms when wielding.

**Comment by Vordenburg** [comment]
Where does it do this? I didn't see any changes to OnDisarmAttemptEvent.

**Comment by Elijahrane** [comment]
that's what the CL claims anyway :slightly_smiling_face:
