### ISSUE TITLE
Psionics are removed on death -- defibs can bring people back from death

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#1627]
## Description

Thus, getting revived via defib doesn't let you keep your psionics.

Not sure what the best solution is or if this is even a bug.

**Comment by Plyushsune** [comment]
so im looking at this articles, it is really strewed because its really varying in information but the most common answer is the brain is just dormant for 5 minutes

**Comment by PrPleGoo** [comment]
having a look at this

**Comment by Vordenburg** [comment]
I think if someone comes back by being defibbed, maybe they could keep their psionics, with some increasing chance of loss similar to how the metempsychotic machine works.

**Comment by PrPleGoo** [comment]
https://github.com/Nyanotrasen/Nyanotrasen/blob/master/Content.Server/Nyanotrasen/Psionics/PsionicsSystem.cs#L136
Dying just removes the PsionicComponent.
Should I make a PsionicsDisabledByDeathComponent and add/remove that on death/alive respectively?

**Comment by PrPleGoo** [comment]
https://github.com/Nyanotrasen/Nyanotrasen/pull/1661 this seems to be a cleaner solution

**Comment by PrPleGoo** [comment]
Psionic powers were (and will be in my PR) cooling down while dead. Is this intended or should I fix that while I'm down here?

**Comment by PrPleGoo** [comment]
Nevermind, that's just a feature of the action system not actually ticking down cooldowns but waiting for a timestamp.
