### ISSUE TITLE
Lobby menu breaks sometimes

### ISSUE THREAD

**Issue by cyf-4** [arcadia-station/arcadia-station#172]
## Description
the menu is navigatable but the chat box is incredibly small

**Reproduction**
after round ended, the bug happened, dont know yet if its repeatable

**Screenshots**
![image](https://user-images.githubusercontent.com/36266916/171253614-390b9323-7a13-4a29-8612-fa698a31b649.png)

**Additional context**
only happened after round ended

**Comment by cyf-4** [comment]
after i completely quit and rejoined, the problem was solved

**Comment by ZeroDayDaemon** [comment]
I've encountered this, but am not aware of a way to reproduce it

**Comment by PrPleGoo** [comment]
I've had this happen to me after round end

**Comment by Elijahrane** [comment]
haven't gotten any reports of this in a while

**Comment by Vordenburg** [comment]
I haven't seen this recently. If it happens again, please re-open with any details you can provide.
