### ISSUE TITLE
Nukie medics wont spawn properly

### ISSUE THREAD

**Issue by DebugOk** [arcadia-station/arcadia-station#1780]
## Description
Their outfit is referencing an invalid prototype, ClothingMaskBreathMedicalSecurity. Which was part of brigmedics I believe.

**Reproduction**
Try to set outfit the nukie medic onto anything, or spawn as one

**Comment by Vordenburg** [comment]
`StartingGearPrototype` was not subject to the linter, resolved in https://github.com/space-wizards/space-station-14/pull/19307
