### ISSUE TITLE
Need a map to replace Atlas

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#279]
## Description

Atlas sucks

**Comment by Just-a-Unity-Dev** [comment]
Thoughts on Saltern?

**Comment by Elijahrane** [comment]
Could be OK if someone wanted to maintain a Nyano version of it.

**Comment by Just-a-Unity-Dev** [comment]
> Could be OK if someone wanted to maintain a Nyano version of it.

Willing to modify Saltern to fit Nyano's needs when I'm not busy
