### ISSUE TITLE
All of the uniform printer recipes need to be replaced with their nyano equilvalents

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#392]
## Description

Bottom text

**Comment by ZeroDayDaemon** [comment]
Create a nyanotrasen specific uniform printer to place on maps

**Comment by Elijahrane** [comment]
> Create a nyanotrasen specific uniform printer to place on maps

don't do this, the issue is specifically with the recipes themselves. lathes and lathe recipes are one of the things this isn't feasible to have seperated

**Comment by Elijahrane** [comment]
partially mitigated because I just deleted all the unused ones

**Comment by Vordenburg** [comment]
I think we got all of this with #1581.  A new issue can be opened if necessary.
