### ISSUE TITLE
Whitelisted roles spawn in the arrivals shuttle.

### ISSUE THREAD

**Issue by Vordenburg** [arcadia-station/arcadia-station#737]
## Description

This is due to the async nature of checking for whitelist. The game round will have moved to the next stage for some of these players by the time the calls come back, resulting in the game selecting late join spawn points.

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Elijahrane** [comment]
i've been coming up with a few ideas to fix this

**Comment by Elijahrane** [comment]
we'll see if we get any reports in the next few days, otherwise i'll close

**Comment by Vordenburg** [comment]
I readied into a round with a whitelisted role yesterday and had no issue. Spawned in the proper spot.
