### ISSUE TITLE
tinned meat doesnt stay deep fried once eaten

### ISSUE THREAD

**Issue by deltanedas** [arcadia-station/arcadia-station#862]
## Description
empty tinned meat doesnt inherit deep fried-ness and i suspect several other items do this too

**Reproduction**
1. open meat
2. deep fry
3. eat it all
4. empty tin is not deep fried

**Comment by Elijahrane** [comment]
Probably going to be a recurring issue with food's trash spawning stuff

**Comment by Vordenburg** [comment]
It's been known to me for awhile, and I haven't settled on a good solution. Mostly cosmetic.

**Comment by Vordenburg** [comment]
I'm going to leave this as-is for now so long as it's a minor cosmetic issue.
