### ISSUE TITLE
Changing the name of ScreenType enum entries breaks people's configs.

### ISSUE THREAD

**Issue by moonheart08** [arcadia-station/arcadia-station#884]
## Description
You're forcibly overriding people's choice regardless of whether or not it was a deliberate one, and additionally making that forced change stick across all servers should they then change their options at any time.

ScreenType should not have it's enum keys renamed, and you shouldn't be tampering with a user's settings across servers, this just causes technical issues for them and a silent config parsing failure for everyone else.

**Comment by ZeroDayDaemon** [comment]
So, If I'm reading this correctly, us changing the default to old chat on nyano affects other servers? That's not intended no, It's only supposed to be for nyano.

**Comment by moonheart08** [comment]
> So, If I'm reading this correctly, us changing the default to old chat on nyano affects other servers? That's not intended no, It's only supposed to be for nyano.

You changed the default by making everyone else's default an invalid config value, so yes it's incompatible with everyone else.

**Comment by ZeroDayDaemon** [comment]
I didnt change it so im not particularly sure how it was changed, but I can take a look at it and try to fix it.

**Comment by moonheart08** [comment]
It was done by rane, and afaict it deliberately relies on the fact that an invalid setting for `ui.layout` just resets to default.

A better option is to simply change the name of the cvar instead so nyanotrasen has it's own distinct UI layout cvar.
